/*
  Generated by kissy-tpl2mod.*/
KISSY.add(function () {
    return '<button class="button {{cls}}" title="{{tooltip}}">\n	<i name="text">{{text}} </i>\n	<i name="icon" class="icon iconfont {{iconCls}}"></i>\n</button>';
});