/*
  Generated by kissy-tpl2mod.*/
KISSY.add(function () {
    return '<div class="main">\n <div class="bar-positive nav-bar-container">\n  </div>\n <div class="view-container">\n \n 	<div name="tab-container" class="tabs-icon-top pane">\n 		<div class="tab-nav tabs">\n 		</div>\n 	</div>\n </div>\n</div>\n';
});