/*
  Generated by kissy-tpl2mod.*/
KISSY.add(function () {
    return '<div class="slider" style="visibility: visible;">\n	<div class="slider-wrapper">\n	</div>\n	\n	<div class="slider-pagination">\n	</div>\n</div>';
});